# claude-task configuration
# Generated by: claude-task init https://github.com/users/kfly8/projects/12
# Generated at: 2025-12-29 11:46:56

# GitHub Project
GITHUB_PROJECT_URL="https://github.com/users/kfly8/projects/12"
PROJECT_OWNER="kfly8"
PROJECT_NUMBER="12"
PROJECT_ID="PVT_kwHOAAsGRM4BLca_"

# Status field
STATUS_FIELD_ID="PVTSSF_lAHOAAsGRM4BLca_zg7BBrc"

# Status options
STATUS_READY_ID="f75ad846"
STATUS_WIP_ID="47fc9ee4"
STATUS_REVIEW_ID="1bb743da"
STATUS_BLOCKED_ID="a40421cf"
STATUS_DONE_ID="98236657"

# Log directory
LOG_DIR="$HOME/.claude-task/logs"
